name: 'jobatlas'
version: '1.0.0'
config-version: 2
profile: 'jobatlas'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  jobatlas:
    staging:
      +materialized: view
      +schema: dbt_staging
    intermediate:
      +materialized: view
      +schema: dbt_intermediate
    marts:
      +materialized: table
      +schema: marts
